version: '3.3'
services:
  app:
    build: .
    environment: 
      DB_HOST: ${HOST_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME:  ${DB_NAME}
    volumes: 
        - ./app:/var/www/html/
    ports:
      - 8000:80
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306